### ISSUE TITLE
BrowserWindow Methods?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [jprichardson/electron-window#1]
First off, fantastic library. I had written a similar script for a project, just using this instead now.

Would it be possible to return the BrowserWindow object, with your additional methods added, so that calls like ```window.getFocusedWindow()``` would be possible? Or could you alias some of the methods from BrowserWindow, e.g. ```window.focused()```?

**Comment by jprichardson** [comment]
When I first saw this issue, my initial inclination was to implement this as it'd be super easy to mix in the class methods on `BrowserWindow`. I'm wondering if it'd be confusing though to people? Why not just require `BrowserWindow`?

**Comment by TuckerWhitehouse** [comment]
So I guess my assumption would be that this library would be a drop in replacement for ```BrowserWindow```, where currently it's just a helper method for creating windows that are unreferenced properly.

I experimented with creating a class that extends ```BrowserWindow``` and overrides the constructor to implement the same sort of functionality, which worked really well, and allowed adding additional methods such as ```toggleFullscreen``` , ```toggleResizable```, ```toggleAuthHideMenuBar```, etc

**Comment by atdrago** [comment]
@jprichardson This can probably be closed. ElectronWindow is a utility supplementing `BrowserWindow`, not a replacement for it.

**Comment by jprichardson** [comment]
I still don't think it's a bad idea. But I'm think that it's not a good time for it yet. I'd like to see Electron API hit stability at 1.0 first. It's close: http://blog.atom.io/2015/11/17/electron-api-changes.html

**Comment by michaelpeterlee** [comment]
I understand where folks get confused. This is false advertising; the README example mainWindow != mainWindow, it's not a BrowserWindow instantiation. createWindow() advertises it creates a new BrowserWindow, however it does not return that. Perhaps the README should be updated to reflect this up front.
