### ISSUE TITLE
replace options.preload with options.webPreferences.preload

### ISSUE THREAD

**Issue by ocpra** [jprichardson/electron-window#11]
When running the app, get the error message

(electron) options.preload is deprecated. Use options.webPreferences.preload instead.

Thanks

**Comment by jprichardson** [comment]
Do you know which version of Electron this change was implemented? Thanks.

**Comment by ocpra** [comment]
Looking at the code, it is deprecated since electron 0.37.3...

Thanks

**Comment by atdrago** [comment]
Confirming this started being deprecated in 0.37.3.
https://github.com/electron/electron/commit/15397bf879b26e56df4d28453a30f04ea915b984#diff-cdea08a8a60584d6c5e52ad5ab4bb67dR277
