### ISSUE TITLE
Electron complains on launch: (electron) options.preload is deprecated. Use options.webPreferences.preload instead.

### ISSUE THREAD

**Issue by capouch** [jprichardson/electron-window#15]
Running electron 0.37.8, and I get this message when I launch an app which is using electron-window.

Is this something fixable with configuration, or is it in the guts of electron-window?

**Comment by jprichardson** [comment]
Are you using version `0.7.0`?

**Comment by capouch** [comment]
No, 0.6.4.

Trying to put in 0.7.0 gives me:

npm ERR! No compatible version found: electron-window@^0.7.x
npm ERR! Valid install targets:
npm ERR! 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.1, 0.1.0

**Comment by jprichardson** [comment]
Ooops, I forgot to publish it 😁  Try now.

**Comment by capouch** [comment]
I installed 0.7.0 and things are now fine!  Thanks for the quick response.
