### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by atdrago** [jprichardson/electron-window#16]
The README examples could use some updates:
- [ ] New methods of referencing Electron modules (e.g., `const { app } = require('electron')` instead of `const app = require('app')`)
- [ ] Usage of ES6 syntax
    - [ ] `const` and `let` instead of `var`
    - [ ] arrow functions
    - [ ] destructuring assignment

Let me know what you think of this. I can do it at some point. Just wanted to write it down so I remember. :)

**Comment by jprichardson** [comment]
This would be awesome, PR accepted :) Thanks!
