### ISSUE TITLE
Error message when closing window

### ISSUE THREAD

**Issue by atdrago** [jprichardson/electron-window#5]
As of Electron v0.35.4, the following error message is shown within an alert dialog whenever a window is closed that was created with ElectronWindow.

Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at BrowserWindow._unref (/Users/adamdrago/Documents/git/negative/node_modules/electron-window/lib/main.js:25:23)
    at BrowserWindow.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)

<img width="420" alt="screen shot 2015-12-05 at 8 15 04 am" src="https://cloud.githubusercontent.com/assets/144225/11608780/5bad4fa2-9b28-11e5-9aff-f5d682701375.png">

I haven't had time to look into the actual cause of the issue. Will update once I know more.

**Comment by atdrago** [comment]
Found this:
https://github.com/atom/electron/commit/973ae06f214122686c501ec28ff5f55e60fd4f0e

I believe it is related.

**Comment by jprichardson** [comment]
I suspect just changing https://github.com/jprichardson/electron-window/blob/0.6.0/lib/main.js#L46 `'closed'` to `'close'` will fix it.

**Comment by jprichardson** [comment]
For reference: https://github.com/atom/electron/blob/v0.34.0/docs/api/browser-window.md#event-close
